### ISSUE TITLE
Options.sol

### ISSUE THREAD

**Issue by TobiasBK** [smartcontractkit/defi-minimal#1]
What are your plans for  Options.sol?
Do plan to include reference to an underlying like ETH/USD?
How do you plan to offer different trading types (long call, short put, etc.)?

If you give a little direction on what you envisioned, I wouldn't mind working on this :)

**Comment by PatrickAlphaC** [comment]
Awesome!!

I think a long call and a short put would be perfect as two options (not sure if more are needed?). I think reference to underlying like ETH / USD would be good too!

I think mainly the ability to:

1. Buy an option
2. Have it be long or short
3. Exercise the option

Is really all we'd need for a minimal version.

**Comment by TobiasBK** [comment]
submitted PR. Let me know if I'm heading in the right direction :)

**Comment by PatrickAlphaC** [comment]
You are in the right direction!!!

**Comment by PatrickAlphaC** [comment]
Closing,  thanks for the PR!
