### ISSUE TITLE
Uniswap v1

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/defi-minimal#2]
Hello,

I can take care of implementing a minimal version of uniswap v1. Found several nice and detailed examples online so I can give it a try. We can have:

- Factory to create several exchanges
- Exchange contract (ETH vs ERC20 Token):
  - Add liquidity
  - Get Reserve of token
  - Get current price of token ( constant product formula)
  - Buy / sell token (swap functions - including fees)
  - Manage liquidity tokens

**Comment by PatrickAlphaC** [comment]
Holy shit that would be nuts. Would love to see this.

We could call it `Swap.sol` (similar to our naming agnostic other ones)

**Comment by aelmanaa** [comment]
ok cool, will work on it !
